// source: ProtocolInfo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  (function () { return this; }).call(null) ||
  Function('return this')();

goog.exportSymbol('proto.ActionButtonId', null, global);
goog.exportSymbol('proto.Hd2Request', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Hd2Request = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Hd2Request.repeatedFields_, null);
};
goog.inherits(proto.Hd2Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Hd2Request.displayName = 'proto.Hd2Request';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Hd2Request.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.Hd2Request.prototype.toObject = function (opt_includeInstance) {
    return proto.Hd2Request.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.Hd2Request} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.Hd2Request.toObject = function (includeInstance, msg) {
    var f, obj = {
      version: jspb.Message.getFieldWithDefault(msg, 1, 0),
      signature: jspb.Message.getFieldWithDefault(msg, 2, 0),
      time: jspb.Message.getFieldWithDefault(msg, 3, 0),
      actionbuttonsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Hd2Request}
 */
proto.Hd2Request.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Hd2Request;
  return proto.Hd2Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Hd2Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Hd2Request}
 */
proto.Hd2Request.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setVersion(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setSignature(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setTime(value);
        break;
      case 4:
        var values = /** @type {!Array<!proto.ActionButtonId>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
        for (var i = 0; i < values.length; i++) {
          msg.addActionbuttons(values[i]);
        }
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Hd2Request.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.Hd2Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Hd2Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Hd2Request.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSignature();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getActionbuttonsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      4,
      f
    );
  }
};


/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.Hd2Request.prototype.getVersion = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.setVersion = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 signature = 2;
 * @return {number}
 */
proto.Hd2Request.prototype.getSignature = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.setSignature = function (value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 time = 3;
 * @return {number}
 */
proto.Hd2Request.prototype.getTime = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.setTime = function (value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated ActionButtonId actionButtons = 4;
 * @return {!Array<!proto.ActionButtonId>}
 */
proto.Hd2Request.prototype.getActionbuttonsList = function () {
  return /** @type {!Array<!proto.ActionButtonId>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.ActionButtonId>} value
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.setActionbuttonsList = function (value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.ActionButtonId} value
 * @param {number=} opt_index
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.addActionbuttons = function (value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Hd2Request} returns this
 */
proto.Hd2Request.prototype.clearActionbuttonsList = function () {
  return this.setActionbuttonsList([]);
};


/**
 * @enum {number}
 */
proto.ActionButtonId = {
  A_BNT_NONE: 0,
  A_BNT_STRATAGEM: 1,
  A_BNT_UP: 2,
  A_BNT_LEFT: 3,
  A_BNT_RIGHT: 4,
  A_BNT_DOWN: 5
};

goog.object.extend(exports, proto);
